on:
  push:
    branches:
      - feat/**
      - release/**
      - dev
      - main

jobs:
  push:
    runs-on: ubuntu-latest
    steps:

      - name: pnpm
        uses: pnpm/action-setup@v6.0.2
        with:
          standalone: true
          cache: true
          package_json_file: package.json

      - name: test
        run: pnpm i

      - name: node
        uses: actions/setup-node@v6.3.0
        with:
          node-version-file: package.json
          check-latest: true
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: test
        run: pnpm run build

      - name: publish
        run: pnpm run publish:chromatic
